### PR TITLE
Adding, tweaking, fixing.

### PR DESCRIPTION
**Pull request by Tenscore**
added Shadeless lighting. (torches, firebowl)
Removed frames from tent decorations. (whoops!)
corpse nulls.
added a bunch of critters.

### CODE REVIEW

**Comment by Tenscore** [comment]
fighting with seperating 'issues' and failed.   Am a noob.

So - latest installment:
Axe :  Removed a safe zone in West ogre caves around a portal area by reconfiguring spawner.   Cleaned up east side spawns for coherence. (and to dispel a myth about double spawns.)

Leng :  Tried to reconfigure it a bit to make it more accessible to mid levels.
1. Toned down the surface mobs a notch.
2. Removed UD Spawns from the Stables.  Created new lvl appropriate Spawns for it and added some in empty spots.

3. Maus - Made sure the presence can cast. Corralled the ConcWiz's to the base of Vlad's tower, and made them invisible. (can see a hex away)  Put in IceWiz's to replace them.  Let the humans and undead mingle a bit more in the south.

Griff Cliffs:  added mobs.  Let the trolls and griffs roam more.  Set out 2 Thief sniffing Ravens and put the bees back.
Scaled back some mobs to make room for them - all in hopes of making it more hunter-diverse.

This is a first try, but I hypothesize that the difficulty won't necessarily change all that much - but may be just a tad easier to survive/wade through.

**Review by SewerCzar — DISMISSED** [review]

**Comment by Chilly021** [comment]
Not sure why we need this if the walls are indestructible here. 
image

**Review by Chilly021 — CHANGES_REQUESTED** [review]
Remove unnecessary exclusion. As mentioned before

**Comment by Tenscore** [comment]
its to keep mobs from spawning in the walls and air hexes - and WF wasn't happy until i put them in.

**Comment by Chilly021** [comment]
Just remove that one and it should be fine. If the wall is indestructible, you have nothing to worry about. Crits do not spawn in walls unless they are down.

**Comment by Chilly021** [comment]
Ah this one too. 
image

**Comment by Tenscore** [comment]
ok, so I'm trying to understand why not there, and why other places.
Can you explain so i can learn?

Kinda feel like you're being nit-picky.  (compared to what was there before.)

**Comment by Tenscore** [comment]
image

from west.

**Comment by Tenscore** [comment]
image

**Comment by Chilly021** [comment]
Right difference being, things do not spawn in walls at up time. Walls come up at initialization, then crits. Pointless to add an exclusion to a wall that is indestructible. Also if you are changing stuff, only then I look at the changed area. I should be done tonight on the code review.

**Comment by Tenscore** [comment]
aah ook, ty. So half of wests exclusions are kinda useless too.

**Comment by Chilly021** [comment]
I haven't been there yet.. having to multi task - it depends. I agree they should be there for destructible walls.

**Comment by Chilly021** [comment]
Yea from what I can tell west too. I think Angry patched those walls that were originally marked destructible to indestructible. @sproatba  might be able to give you some detail: 

image
image
image

**Review by Chilly021 — APPROVED** [review]

**Review by zrikzlok — APPROVED** [review]

**Pull request merged**
