### PR TITLE
CornerWallFixes

### PR DESCRIPTION
**Pull request by sproatba**
add new corner art for dungeon and town to kes/leng/oak.
every level of kes was affected.
leng is primarily ud but a couple stray fixes south of town and the green connecting dungeon to stables
oak has some on surface but it's primarily serp level and 1 on tt.  Also fixed a few missed corners in the previous update (serp and tt)

### CODE REVIEW

**Review by yarrim — DISMISSED** [review]
I think parts of this got rolled into the Oak Confessor Ghost addition pull too, #1501 
Might need to revert the oak mapproj change here to avoid a merge conflict.

**Comment by yarrim** [comment]
#b0d6601
This seems to have pieces of your MonsterManual embedded in it. I'd like to ensure those are intentional by making them part of a separate pull.

**Comment by sproatba** [comment]
i'll split this out into 3 prs

**Comment by sproatba** [comment]
separated into 3 new prs this one can die

**Pull request closed without merging**
