### PR TITLE
bloodlands fixes

### PR DESCRIPTION
**Pull request by zrikzlok**
fixed teleporter and made some slight adjustments to Exp/hp values for the planes to be a little more in line with Sewers area to make them at least somewhat appealing until we do full exp/hp refactor. Also added some random hexes within the various planes to allow for exit.

Temple of the planes now also has recall/balm vendor

### CODE REVIEW

**Review by SewerCzar — APPROVED** [review]
thumbs up

**Comment by zrikzlok** [comment]
@jkachhad hmm, something weird happening? Sewer reviewed and approved, but says it still needs to be reviewed. Worked fine last night

**Review by Tawnos-LOK — APPROVED** [review]
Changes look good and are consistent with comments.

**Review by Leolus — APPROVED** [review]

**Review by Chilly021 — APPROVED** [review]

**Comment by Chilly021** [comment]
Sorry I approved another one yesterday, @zrikzlok  you can merge I assume.

**Pull request merged**
