### PR TITLE
Various UK Fixes

### PR DESCRIPTION
**Pull request by trlook**
--Temp Fix: Changed portal behind TK from Item to Hidden
--HummingBirdGhost: Fix spawn location, Give 1hr Respawn, Add Cast Delay to WW and decrease damage, Decrease Health
--Fixed some OL Wraith Spawns
--Fixed some surface Lurker Spawns
--Fixed Recall Vendor
--Added Thieves Guild TP to stop non thieves from entering
--Added PP amulet, S/D Bracer and Purple robe to OL loot
--Adjusted Drakes 3rd Attack

### CODE REVIEW

**Comment by SlysterLOK** [comment]
Awesome. A few of these were waiting to be pushed like the thief guild teleport. Good to make sure these are caught though.
Also go ahead and change the OLWraiths to Mummies like they were in the OG. :)

**Comment by trlook** [comment]
> 
> 
> Awesome. A few of these were waiting to be pushed like the thief guild teleport. Good to make sure these are caught though.
> Also go ahead and change the OLWraiths to Mummies like they were in the OG. :)

I seem to remember them being wraiths in that hallway though?

**Comment by SlysterLOK** [comment]
> > Awesome. A few of these were waiting to be pushed like the thief guild teleport. Good to make sure these are caught though.
> > Also go ahead and change the OLWraiths to Mummies like they were in the OG. :)
> 
> I seem to remember them being wraiths in that hallway though?

They were mummies in the original game. Even the lore refers to them as mummies.

**Comment by trlook** [comment]
I remember there being mummies in his lair for sure... was it mummies in the trapped hallway too?

**Comment by SlysterLOK** [comment]
> I remember there being mummies in his lair for sure... was it mummies in the trapped hallway too?

Yep. They were insta cast curse mummies.

**Pull request merged**
