### PR TITLE
Change silver greataxe from axe to greataxe

### PR DESCRIPTION
**Pull request by sproatba**
Fix sga label and make it's category match the art category.

### CODE REVIEW

**Comment by sproatba** [comment]
Closes #1469

**Comment by sproatba** [comment]
#1469

**Comment by Chilly021** [comment]
Wouldn't this make it a true 2h? or no?

**Comment by sproatba** [comment]
> Wouldn't this make it a true 2h? or no?

no, we would need to override fumble to make it true twohand currently

**Review by Chilly021 — APPROVED** [review]

**Review by zrikzlok — APPROVED** [review]

**Pull request merged**
