### PR TITLE
Leng Bridge Troll Can Charge Now

### PR DESCRIPTION
**Pull request by Chilly021**
The leng bridge troll needed some flair. Keep the Bridge Troll to be 2 hex movement, but make sure he can charge. He can only melee, so could easily be outran by adventures still, unless of course in sand.. muhahaha.

### CODE REVIEW

**Review by SewerCzar — APPROVED** [review]

**Review by Leolus — APPROVED** [review]

**Review by SewerCzar — DISMISSED** [review]

**Comment by Tawnos-LOK** [comment]
Looks like there's an older commit that snuck in there too (cd77a5c) that's unrelated

**Comment by Chilly021** [comment]
Anyone know how to revert the git history there? I fetched / pulled and merged from Master to my Fork. Then they showed up even though Git Commits were from the Fork originally.

**Comment by Tawnos-LOK** [comment]
> Anyone know how to revert the git history there? I fetched / pulled and merged from Master to my Fork. Then they showed up even though Git Commits were from the Fork originally.

You could do an interactive rebase (-i) and drop or comment out that one commit

**Comment by Chilly021** [comment]
Need to get latest from main. I'm going to kill this remote and bring it back.

**Pull request closed without merging**
