### PR TITLE
Art Adds and an overlap fix at 1007

### PR DESCRIPTION
**Pull request by Tenscore**

### CODE REVIEW

**Review by SewerCzar — APPROVED** [review]

**Comment by Chilly021** [comment]
There is a lot here.

**Review by SewerCzar — APPROVED** [review]

**Review by Chilly021 — APPROVED** [review]

**Comment by Tenscore** [comment]
Mostly from the renumbering.  Shifting them all up a number from the 1007 id conflict.

**Comment by Tenscore** [comment]
Testing it in Worldforge gave me an error.  Moving everything up a number fixed it.
I figured it had something to do with the fix from yesterday leaving one out.  1000-1006.

**Comment by sproatba** [comment]
could be, i don't think it's broken but won't hurt to do it

**Review by sproatba — APPROVED** [review]

**Pull request merged**
