### PR TITLE
Add Description for Fire and Ice Amulet

### PR DESCRIPTION
**Pull request by Chilly021**
Currently it's blank so it does not even have a description. When identified it just says 3 of 3.

### CODE REVIEW

**Comment by sproatba** [comment]
was looking this over and noticed the f/i amulet default constructor is passing in the art for the pink pearl locate amulet, do you want to add that to this pr as well?  they both should be 5

**Comment by Chilly021** [comment]
> was looking this over and noticed the f/i amulet default constructor is passing in the art for the pink pearl locate amulet, do you want to add that to this pr as well? they both should be 5

Thanks! was just looking for description. Updated with your find.

**Comment by jkachhad** [comment]
The current modification actually makes it 5 charges, does not change the art. Need to change that on base(5)?

**Comment by Chilly021** [comment]
image

**Comment by sproatba** [comment]
good call I missed the this vs base interaction there.

**Review by yarrim — APPROVED** [review]

**Review by SewerCzar — APPROVED** [review]

**Pull request merged**
