### PR TITLE
Graphics updates and adds

### PR DESCRIPTION
**Pull request by Tenscore**

### CODE REVIEW

**Review by Chilly021 — COMMENTED** [review]
I am seeing a lot of images not rendering and also some strange pathing changing here. 
image

@zrikzlok  @yarrim  might be able to give feedback? I am again not an art / asset fella. Lux reminded to make sure the naming coventions/pathing were all similar. Noticing that some folders have casing inconsistencies but look correct? 

image

**Comment by Tenscore** [comment]
im trying to move dogmen into the gnolls.   they're being used as gnolls, though technically 'lesser gnolls'.
it is my aim to delete the dogmen folder altogether (but wont let me yet as its in use.)

To the rendering - thats github.  perhaps bc of the volume of pictures?

**Comment by Chilly021** [comment]
Happy to give an approval if someone more experienced on the art front can give a look see. Just not my area.

**Comment by Tenscore** [comment]
Click the 3 dots on the right, and 'view file' - for the 'unable to render' images.  They're there, and they're fine.
Git conveys that i have deleted some, over-written some, and moved some to a different directory.

Consolidation.   For cleanliness.   On purpose.

I also found some wrong 'categories' that i fixed in the item.xml, as well as having to point things to the new directory. (from dogmen>gnolls)

An issue came up, and Github inserted lines in the xml because it had changed.  (I hate that it does this.)  I corrected it.
No Conflicts.

**Comment by Tenscore** [comment]
> One note here, I noticed that Items/items is used interchangeably in the pathing. The Attack Jade Dagger might need to change to lower case "items"? image

fixt.  "Items" is the correct directory casing.

**Review by zrikzlok — APPROVED** [review]

**Review by Chilly021 — APPROVED** [review]

**Review by sproatba — APPROVED** [review]

**Pull request merged**
