### PR TITLE
OLD IGNORE / DELETE / CLOSE

### PR DESCRIPTION
**Pull request by SlysterLOK**
Added ropes to the climb down area from Kes Surface to -3 and from Kes-1 to Trog level. Should be able to double click tile and not fall now. Previously ' climb down ' command kept your from falling but I thought new players would click before anyway. And the fall from Surface to -3 is a killer.

### CODE REVIEW

**Comment by SlysterLOK** [comment]
Edited a couple of static components. Very small.

**Comment by SlysterLOK** [comment]
I want to test a single simple change on the nomads in the Leng griff cliffs. Gave nomads an extra attack to choose from instead of always a heavy damage range attack.

**Comment by SlysterLOK** [comment]
Lowered HP slightly on ranged using mobs in Kes -1 and Kes -2 and Kes -3 based off feedback from Fighter classes. Should more easily be able to deal with them with the basic thrown weapons.

**Comment by SlysterLOK** [comment]
Slightly increased the potion pull rate in -4 Kes from .2 to .33 which is ~1500 kills vs ~1000 kills for a possible potion. Also lowered the chance the potion is a DP. Currently a DP was weighted to be 40% of potion drops. It is now the lowest probability potion.

**Comment by jkachhad** [comment]
You may have to update to master on your branch to resolve the Leng conflict

**Comment by SlysterLOK** [comment]
> You may have to update to master on your branch to resolve the Leng conflict

Thanks! I did not realize I was behind on commits. I miss the old way of everything being connected directly to Github Desktop lol

**Comment by SlysterLOK** [comment]
Fixed some walls at Ydnac surface , fixed a typo on a wyvern attack and cleaned up some spawns in Ydnac secret.

**Comment by SlysterLOK** [comment]
Testing out NPC speech. Also am trying it on a couple mobs in Kes -1.

**Comment by SlysterLOK** [comment]
Dove in head first with additions in speech , attack messages and balance tweaks. I thought we were close in Kesmai but I see so much more that can be done to assist and help new players become hooked.

**Comment by SlysterLOK** [comment]
Even more speech and I hope by class and gender.. We'll see!

**Comment by SlysterLOK** [comment]
Added class teleport to the UK thieves guild entry door.

**Pull request closed without merging**
