### PR TITLE
Need more help on thaum summon. This again is for testing. If too pow…

### PR DESCRIPTION
**Pull request by Chilly021**
…erful, which I assume it might be, it will be scaled back

### CODE REVIEW

**Comment by Wirednuke** [comment]
My name is Brick, and I approve this message.

**Comment by dedmist** [comment]
Is there a way to get the caster info during construction?  Ideally they would scale hp/block with magic level.

**Review by SewerCzar — APPROVED** [review]

**Comment by SewerCzar** [comment]
> Is there a way to get the caster info during construction? Ideally they would scale hp/block with magic level.

Scaling 100% needs to happen. I think it's on Lux's huge list of stuff to do.

For now, 1200 defense on a level 9 spell (phantoms are 9, right?), 1250 on an 11, and 1500 on a 17 spell are solid. Especially since they can't balm or really defend themselves. Worst thing that happens is thaums are SLIGHTLY overpowered for a while and that's fine.

**Review by dedmist — APPROVED** [review]
Fair enough

**Review by Leolus — APPROVED** [review]

**Pull request merged**
