### PR TITLE
Shu

### PR DESCRIPTION
**Pull request by Miidgiit**
New area in -200
New boss who uses whirlwind
2 new minibosses
MU only area with teleport phase puzzle.
gnoll raider can swim now.

### CODE REVIEW

**Review by Chilly021 — CHANGES_REQUESTED** [review]
I'm seeing a lot of overlapping components here. You might just remove statics and keep your stair case. 
image

**Comment by Chilly021** [comment]
Some of the water teleports go no where. Is that intentional? 
image

**Review by Chilly021 — COMMENTED** [review]
You can remove these fellas. These were just a safeguard. Now that we have the proper "AddStatus", no longer need these two. 

tiger.AddImmunity(typeof(BlindSpell));
tiger.AddImmunity(typeof(FearSpell));

**Review by Chilly021 — COMMENTED** [review]
Confirmed with @Miidgiit  - we are okay here. Strictly consmetic

**Review by Chilly021 — APPROVED** [review]
It was strictly cosmetic.

**Review by Leolus — APPROVED** [review]

**Review by zrikzlok — APPROVED** [review]

**Pull request merged**
