### PR TITLE
Kes UD Spawn Update

### PR DESCRIPTION
**Pull request by SlysterLOK**
Increased the spawn as it was pretty barren felt like.

The 2 mini bosses were also not spawning so I just through them in their own region spawn instead of doing a sub region for the lair since they will roam the whole area anyway.

Tweaked the map a bit as well.

### CODE REVIEW

**Comment by SlysterLOK** [comment]
Oops! No problem. Thanks for pointing that out again. Slipped my mind

**Comment by Chilly021** [comment]
Just in case, see dev channel. If you could change this back to X = 1 and Y = 1 
image

**Comment by SlysterLOK** [comment]
Done

**Review by Chilly021 — APPROVED** [review]

**Comment by sproatba** [comment]
image
May need to adjust the no recall zone or add some spawns in the new hallway or something.

**Comment by sproatba** [comment]
image
are the ydnac -1 areas supposed to still be there?   If so should they be renamed to the kes 3.5?

**Comment by sproatba** [comment]
image
spawns here can end up where no player can get to, and potentially can walk off the map or something else odd.  I think we want an exclusion here.

**Comment by sproatba** [comment]
image
same over here

**Comment by sproatba** [comment]
image
looks like these two spawns regions were orphaned with a region change.

**Comment by SlysterLOK** [comment]
Doesn't look like you have the newest push. I can tell because the solo mummy spawns are gone and the segment has been renamed already.

I have the water as an exception but haven't committed it yet.

I don't think the hall needs to be no recall or have mobs since the area south and West aren't no recall nor does it have mobs. If anything I would remove those stairs and hall.

**Comment by SlysterLOK** [comment]
I went back and look and you were right! Somehow those spawn regions were still active. I am positive I deleted those before even starting the expansion work. Oh well. Taken care of now.

**Comment by SlysterLOK** [comment]
Ok. Updated. Maybe this one will suffice.

**Comment by SlysterLOK** [comment]
I cannot for the life of me find the issue. I've deleted rewrote each change and still cannot get to the bottom of it.

**Comment by SlysterLOK** [comment]
Ok I finally got it. I had to roll back a bit but I think I got it all ready to go.

**Comment by sproatba** [comment]
image
image
I don't think we can use 4.5 for skill level.  If it does compile I think it just does lvl 4 damage.

**Review by sproatba — APPROVED** [review]

**Review by Chilly021 — APPROVED** [review]

**Review by zrikzlok — APPROVED** [review]

**Pull request merged**
