### PR TITLE
Normalize Axe Surface Gems with -3 gems. -3 is easier than axe surface

### PR DESCRIPTION
**Pull request by Chilly021**
* Upped the gem value to be "Slightly" higher than -3 gems 
-3 kesmai is based on Level 5 crits 
Axe Surface is based on Level 6 crits

image

### CODE REVIEW

**Comment by sproatba** [comment]
are you also taking into account quantities here?  axe surface seems to drop a lot more gems than kes -3 so the overall gem value might be "ok".   Surface is a bit hard to judge though because so many people saturate it.

**Comment by Chilly021** [comment]
I just changed the drop %. I forgot about that. Should be less gems dropping for more value.

**Review by SewerCzar — CHANGES_REQUESTED** [review]
My personal opinion is double gem values (20k nugget 1700 emerald 3200 uncut diamond) and put the drop rate at 7.4 and I'd be happy with it, if that seems fair.

**Comment by Chilly021** [comment]
Checking it now.

**Review by SewerCzar — APPROVED** [review]

**Review by sproatba — APPROVED** [review]

**Review by zrikzlok — APPROVED** [review]

**Pull request merged**
