### PR TITLE
Update Kesmai -5

### PR DESCRIPTION
**Pull request by Miidgiit**
added NightVision to my kesmai -5 creatures
added higher timer to huemongus
darkened the zone. Will darken it further later.
changed the northwest PORTAL to hopefully teleport the player to BLOODLANDS
fixed the reason why my second blood ghoul was not spawning.
added Teleports to push players away from the EMONDEUS gates.
Will balance WRAITHS and LOOT in future update.

Chilly
Went back and balanced skeletons and their loot. 
Add Demon body to Demon (masked as a Dragon)

### CODE REVIEW

**Review by Chilly021 — APPROVED** [review]

**Review by Chilly021 — DISMISSED** [review]

**Review by zrikzlok — DISMISSED** [review]

**Comment by sproatba** [comment]
image
got some walls that need fixed
image

**Comment by sproatba** [comment]
image
there are a few areas like this where the terrain isn't quite right.  the floor tile should be removed in this case so the black wall is visible.  I don't think it will cause any issues other than look wrong visually.
image

**Comment by sproatba** [comment]
left 2 sewer spawner has nothing to spawn in it.

**Comment by Miidgiit** [comment]
yeah I halfassed the darkening of the zone.Was going to finish that after this update. 
Left 2 sewer will have piranhas in the future. it must have glitched out.

**Comment by Chilly021** [comment]
-5 changes are up @sproatba @Miidgiit @zrikzlok

**Review by Chilly021 — APPROVED** [review]

**Review by sproatba — APPROVED** [review]

**Review by zrikzlok — APPROVED** [review]

**Pull request merged**
