### PR TITLE
bloodlands updates / enhancements

### PR DESCRIPTION
**Pull request by zrikzlok**

### CODE REVIEW

**Comment by Leolus** [comment]
Quest cs file in the Development channel for str quest. Can be found with "Here's the quest for 18 str"

**Comment by zrikzlok** [comment]
[EighteenStrengthQuest.cs.txt](https://github.com/jkachhad/Stormhalter/files/7169217/EighteenStrengthQuest.cs.txt)

**Comment by zrikzlok** [comment]
[EighteenStrengthQuest.cs.txt](https://github.com/jkachhad/Stormhalter/files/7169511/EighteenStrengthQuest.cs.txt)

**Comment by zrikzlok** [comment]
[OrnateHalberd.cs.txt](https://github.com/jkachhad/Stormhalter/files/7172140/OrnateHalberd.cs.txt)
if you happen to put this in, give me a 60 second notice so I can add it to a boss loot table and push super quick, or if you can throw it into forestBoss3 with like 25% drop rate please sir! ultimately will probably shoot to make it a quest once I see if it's working properly.

**Comment by jkachhad** [comment]
I just realized what you were asking me, no the 0.3 on the Mana regen won't work.

**Pull request merged**
