### PR TITLE
Fixed grove heart

### PR DESCRIPTION
**Pull request by SewerCzar**
Turned grove from sloppy shield shape to actual heart shape

Evened out spawns with a <.20 density and 25-30 minute respawn (pre-adjustment)

Removed the random cat demons that prevented the zone from being particularly farmable.

Increased gems to be equivalent to axe undead - difficulty should be similar.

Revamped escort quest - just one cat demon resides in the aorta passage, killing it will despawn the obstacles and begin the escort but the escort is farther now. 

Upon finish of the escort quest a boss is released from behind the blocked pulmonary veins.

### CODE REVIEW

**Comment by zrikzlok** [comment]
Pretty dang cool looking map I must say, have only minimally played in grove but this looks interesting.

**Review by zrikzlok — APPROVED** [review]

**Review by Leolus — DISMISSED** [review]

**Review by Chilly021 — CHANGES_REQUESTED** [review]
Naming of variables is not following conventions already used prior. 
image

Additionally there are many changes not listed here. 

* Stairs up to Teleporter to Sea Serpent 
* Moved Sogmallon to heart necro spawner (assuming this is the update: just one cat demon resides in the aorta passage, killing it will despawn the obstacles and begin the escort but the escort is farther now.)
image

* Aorta is brand new and can be entered through two drops
image

**Comment by SewerCzar** [comment]
> I don't see anything technically wrong here. Balancing might be an issue as mentioned. I'll be interested to see how all the area strips will work out for mob flow. I think fix up what chilly pointed out and we are good

image

Already exists

image


No idea what this means? Thats the total number of packs? Density is sub .2

I have NO clue why every single spawn is posted but densities are sub .1 on each individual spawner and sub .1 on the entire spawner.

Spawner being done this way is best practice now.

image

Grouping them together as GroveHeart is also best practice? 

I'm really confused by every single spawn being posted here. We can see density, we can see location, we can see they're within density norms and respawn slightly slower?

And the aorta section is just a part of the new map it isn't notable at all?

And the Boss NPC in the pond won't leave that section as he's tethered by his spawn.

Honestly just confused here

**Comment by SewerCzar** [comment]
> I guess we can fix it for you? Please let us know if you need us to commit the changes.

I responded to all of your weird post. Fix what? All I see in that post is a bunch of screenshots of spawns that don't need fixing, and a set of stairs that already exists. 

Number of monsters is equivalent to axe - I have no idea why thats mentioned - see above about density being like Axe.

Spawns are split up in a way thats... entirely normal? It's spawns with multiple boundaries? This works in the game in every single map, as it's currently in use.

Stairs to the grove heart already exist - see above

Boss monster spawning in pool - he will never leave that one section which won't be used for hunting at all, and is outside for testing.

What needed fixing? This is such a bizarre "request"

**Review by Chilly021 — CHANGES_REQUESTED** [review]
Please correct naming conventions and we should be good here. A few of us spoke.

**Review by Chilly021 — APPROVED** [review]

**Review by SewerCzar — COMMENTED** [review]
Naming conventions have been settled on - lowercase one string.

Previous prove monsters have been sectioned off with a groveEntrance label instead of just grove.

**Review by sproatba — APPROVED** [review]

**Comment by Chilly021** [comment]
> Naming conventions have been settled on - lowercase one string.
> 
> Previous prove monsters have been sectioned off with a groveEntrance label instead of just grove.

thank you, sorry to be a pain.

**Review by zrikzlok — APPROVED** [review]

**Pull request merged**
