### PR TITLE
Wizards be Wizarding, harry. Also Sea Serpent to be Vamp Hide as in l…

### PR DESCRIPTION
**Pull request by Chilly021**
…ands/OG

1) Fix Sea Serp Visibility 
image

2) Fix Fire Wizard Pile Up
image

3) Fix Movie scene to not say anything to killer on death. Due to the AOE of Jim, other crits can kill him. Causing a race condition that could potentially crashes the server.

### CODE REVIEW

**Review by SewerCzar — COMMENTED** [review]
Increase the minimum mobs with the maximum please on wretches - We can randomize spawns later but it's just a mess when it's done right now. 

Why does sea serpent need 3500 more gold?

**Comment by Chilly021** [comment]
We don't need it he's a bit of a lvl 11 mini boss. He poisons too

**Comment by Chilly021** [comment]
> Increase the minimum mobs with the maximum please on wretches - We can randomize spawns later but it's just a mess when it's done right now.
> 
> Why does sea serpent need 3500 more gold?

Will do

**Comment by Chilly021** [comment]
@SewerCzar updated

**Review by SewerCzar — APPROVED** [review]

**Comment by Chilly021** [comment]
@SewerCzar  for whatever reason, Enchant "on death" didn't save. Needed to remove both until we fix the AoE problem.

**Comment by sproatba** [comment]
sea serpent in og could randomly drop any item in the leng loot table,  you were very likely to get a balm, but rarely could get a torc.  Not sure if we want to do something with that here, but a nod to the random loot could be cool.  Not sure going so far as putting a torc is necessary, but if it's a tiny percent i'm not against it.  Lands did something similar, but very limited on what it dropped.

**Review by sproatba — APPROVED** [review]

**Review by SewerCzar — APPROVED** [review]

**Comment by Chilly021** [comment]
> sea serpent in og could randomly drop any item in the leng loot table, you were very likely to get a balm, but rarely could get a torc. Not sure if we want to do something with that here, but a nod to the random loot could be cool. Not sure going so far as putting a torc is necessary, but if it's a tiny percent i'm not against it. Lands did something similar, but very limited on what it dropped.

Yea for now I just spawned it the other day. It there in the code already. I noticed it does present a little of a challenge and will represent a bit more once visibility 0 is done. So I only upped the gold for now in order to present a reason to do it.

**Review by Leolus — APPROVED** [review]

**Pull request merged**
