### PR TITLE
blooadlands progression revamp

### PR DESCRIPTION
**Pull request by zrikzlok**
lotta updates to allow for natural progression from UK to bloodlands, starting around lvl 16

### CODE REVIEW

**Comment by zrikzlok** [comment]
all loot removed except for gold / gems until we determine a plan for future itemization / questions

**Comment by zrikzlok** [comment]
huge credit to sewer for all of the tedious work

**Review by SewerCzar — APPROVED** [review]
Reviewed as much as I can. Suspect that Lux will have to fix a few ;'s but that's natural.
@jkachhad if you want to "test" this before it goes in it might save you a couple minutes at 10 pm.

Other than that looking forward to testing.

**Comment by Chilly021** [comment]
Good job guys

**Review by Leolus — APPROVED** [review]

**Review by Chilly021 — APPROVED** [review]

**Pull request merged**
