### PR TITLE
Fix Blackburrow Thaum Trainer

### PR DESCRIPTION
**Pull request by Chilly021**
1) Switched around the Trainer code to spawn -> location. 
2) Use only two counters similar to Kesmai.

### CODE REVIEW

**Review by SlysterLOK — APPROVED** [review]

**Review by SlysterLOK — COMMENTED** [review]
Things like this shouldn't remain in limbo.

**Comment by sproatba** [comment]
#load "WorldForge"
void OnAfterSpawn(Spawner spawner, MobileEntity spawn)
{
    if (spawn is ThaumaturgeTrainer trainer)
    {
        trainer.Name = "Tvecie";
        trainer.Body = 48;
        
        trainer.AddCounter(new Point2D(25, 7, 10));
        trainer.AddCounter(new Point2D(26, 7, 10));
        trainer.AddCounter(new Point2D(27, 7, 10));

        // This was set to max 14 in template. Why?
        trainer.SetTraining(Skill.Magic, 8, 16);
    }
}

Not sure what changing the terrain was about, but the trainer doesn't have the code to add a counter. This is from the oak thaum trainer.  I believe that is what is needed to fix this guy.

**Comment by Chilly021** [comment]
Will take a look.

**Comment by Chilly021** [comment]
> #load "WorldForge" void OnAfterSpawn(Spawner spawner, MobileEntity spawn) { if (spawn is ThaumaturgeTrainer trainer) { trainer.Name = "Tvecie"; trainer.Body = 48;
> 
> ```
>     trainer.AddCounter(new Point2D(25, 7, 10));
>     trainer.AddCounter(new Point2D(26, 7, 10));
>     trainer.AddCounter(new Point2D(27, 7, 10));
> 
>     // This was set to max 14 in template. Why?
>     trainer.SetTraining(Skill.Magic, 8, 16);
> }
> ```
> 
> }
> 
> Not sure what changing the terrain was about, but the trainer doesn't have the code to add a counter. This is from the oak thaum trainer. I believe that is what is needed to fix this guy.

Not too sure.  Code already has the following:

` shven.AddCounter(new Point2D(30, 7, 1));
    shven.AddCounter(new Point2D(31, 7, 1));
    
    foreach (var skill in Skill.Weapons)
        shven.SetTraining(skill, 0, 8);
    
    shven.SetTraining(Skill.Magic, 0, 19);
    `
    
 The difference is this is set at the entity code, versus Oak is set at the Location code.

**Comment by Chilly021** [comment]
@sproatba  @Leolus  @dedmist @zrikzlok good to go.

**Comment by sproatba** [comment]
I took another look at this, the 2 counters are at 6, -37, 1 and 7, -37, 1.  Might not have needed to move the code as the old code had the wrong locations.  Either way, I think this should work now.

**Review by zrikzlok — APPROVED** [review]

**Pull request merged**
