### PR TITLE
WeaponFlagFix

### PR DESCRIPTION
**Pull request by trlook**
Should fix weapons with multiple flags seeing stacked armor. Highly recommend this gets tested on a local build first. Addresses issue  #739 halberds trigger extra defenses on target

### CODE REVIEW

**Review by SewerCzar — DISMISSED** [review]
I like the change but I'm not qualified to check that code. Looks good on my end

**Review by dedmist — APPROVED** [review]
I'm assuming that ArmorProtections is defined to determine which single bonus to use.  Looks fine.

**Comment by jkachhad** [comment]
What happens in the case that an armor protects against multiple damage types, and against a weapon that deals multiple damage types?  Does it just use the minimum?

**Comment by trlook** [comment]
> What happens in the case that an armor protects against multiple damage types, and against a weapon that deals multiple damage types? Does it just use the minimum?

The original implementation was that a multiple type weapon like halberd (blunt/slash) would see both types of defense. Almost all armor has blunt/slash/pierce protection in equal measure, so it would get double penalized before. Now, it should just check which of the protections is lowest as if smartly attacking with the weapon to be more effective.  We could also average the protections instead such that some of the attacks are more effective if the defender is lacking a protection against a type.  But since most things have multiple protections anyways, the usual behavior will be that a multitype weapon will perform the same as a single type weapon instead of worse.

**Comment by jkachhad** [comment]
Looks good. I changed list to just a byte array to minimize memory allocations since this will likely execute quite often.

**Review by jkachhad — APPROVED** [review]

**Review by Leolus — APPROVED** [review]

**Pull request merged**
