### PR TITLE
Artfix - external body ID re-factor

### PR DESCRIPTION
**Pull request by Tenscore**

### CODE REVIEW

**Comment by Tenscore** [comment]
darkcloud
stormcloud-Sheet
whitebunny
whiterabbit
skeletonpikeman
yetiskull
magehatblue


Seems that its not finding these.

**Comment by Tenscore** [comment]
Re-adding original art i apparently replaced.

This is why I ask about starting points.  Sorry everyone.

**Review by Leolus — DISMISSED** [review]

**Review by Chilly021 — APPROVED** [review]

**Comment by Chilly021** [comment]
@yarrim Please see this.

**Review by Leolus — APPROVED** [review]

**Review by yarrim — COMMENTED** [review]
I think this looks almost OK. My only concerns are:

A net removal of a few .png files:
image
The overall PR doesn't reference these, only an individual commit after the original merge, so maybe they will not be not touched? They already exist in the master repo, so if they are not present in there after merge, they will need to be re-added. I'd probably add them to your (Tenser) local repo to ensure they stick around.

The Content.Stormhalter-External.mgcb seems to be missing references to the net-new images: magehatblue.png, yetiskull.png, skeletonpikeman.png, whitebunny.png, whiterabbit.png.

**Comment by Tenscore** [comment]
Put them back in my local repo.
Mod incoming.   Thank you, nice catch on the mgcb!

**Review by yarrim — DISMISSED** [review]

**Review by Chilly021 — APPROVED** [review]

**Review by yarrim — COMMENTED** [review]
@Tenscore The corpses need to be items instead of bodies:
scorpion (5300)
white rabbit (5310)
white bunny (5311)

**Review by yarrim — APPROVED** [review]
@Tenscore Next PR, could you insert a comment about what the category IDs mean to the top of the items-external.xml? See the comment section about order values in the terrain-external for what I'm asking for.  Alternatively, if you have anything resembling an ID-to-usage scrap, I'll create the comment if you send it to me.

Otherwise, this looks good to me and passes basic syntax checks.

**Review by Chilly021 — APPROVED** [review]

**Review by sproatba — APPROVED** [review]

**Pull request merged**
