### PR TITLE
Thief Trainer in Lockpick Town

### PR DESCRIPTION
**Pull request by Wirednuke**
Added a Thief Trainer to lockpick town, giving thieves a training option that allows them the ability to push gold from a bank. 

Created a Thief area behind a secret door to the north of the wizard trainer in lockpick. 

Second Commit added a teleporter to keep the riff raff out of the thieves guild.

### CODE REVIEW

**Review by dedmist — APPROVED** [review]
I don't see a problem with this.

Looks like you forgot to add a barrel or two along the path though.

**Comment by Chilly021** [comment]
Probably need to do something about the other trainer? Just figure this makes the other obsolete being so close.

**Review by Tawnos-LOK — APPROVED** [review]
I think Lockpick Town thematically makes sense for this so I'm appoving.  Some suggestions for the future - maybe add another door by Lamont (banker) to connect to the back hallway to the east and add one barrel along the path to avoid.

Also, to Chilly's point, something will have to be done with the preexisting trainer down below by the rope.  Possibly just removed / possibly made into a vendor (thief only?).

**Comment by jkachhad** [comment]
Solution coming to gold weight. I would try to say rather than band-aid a fixes in (banker vendors), is there a game-play feature we can create for players to invest into?  I’ll implement it this weekend :)

**Comment by jkachhad** [comment]
New rings added to add some meta to hunting and gold carrying.

**Pull request merged**
