### PR TITLE
Attemp to fix princess scroll so it can be sacked

### PR DESCRIPTION
**Pull request by sproatba**
I know there is some work to overhaul this, just wanted to see if this works for experimentation purposes

### CODE REVIEW

**Review by Chilly021 — APPROVED** [review]

**Comment by SewerCzar** [comment]
> I know there is some work to overhaul this, just wanted to see if this works for experimentation purposes

Changing items in segment is the cause of a lot of the crash. Half the time I've edited an existing item it's created a server crashing bug that causes server to come up NPCless. I'm comfortable doing this if it's added on a night Lux is around. Can we confirm he'll be on at 1 am?

**Comment by sproatba** [comment]
Works for me, if this is dangerous let's wait for Lux.

**Comment by Chilly021** [comment]
I'm only approving this because... It would be nice to have scroll in bag. Though if we have an alternate fix .. just let us know

**Comment by SewerCzar** [comment]
> I'm only approving this because... It would be nice to have scroll in bag. Though if we have an alternate fix .. just let us know

The problem is that segment item change code is prone to bugs. Let me write up why my code works let's see if you guys have confidence (it fixes the whole craft, scroll craft, princess thing as well)

**Comment by SewerCzar** [comment]
> I know there is some work to overhaul this, just wanted to see if this works for experimentation purposes

I explained the overhaul in the other thread. I hope it makes sense. No worries if it doesnt and we can get this in place sooner rather than later.

**Comment by sproatba** [comment]
closing this as we have an overhaul in progress that will be a better fix

**Pull request closed without merging**
