### PR TITLE
Main Gauche added to Lich twins

### PR DESCRIPTION
**Pull request by Wirednuke**
After a long discussion with the fellas in voice chat, we decided it would be better to toss my new Main Gauche defense dagger on the Lich Twins. They are underutilized, and they are a relatively low barrier to entry for a thief. 

For now I have it dropped in the container, I realize that this could be easily abused but traditionally the Lich twins use hand skill so I didn't want to mess that up.

### CODE REVIEW

**Review by Chilly021 — DISMISSED** [review]
That will be fun

**Review by dedmist — APPROVED** [review]
Works for me

**Comment by SewerCzar** [comment]
I don't think adding a one handed weapon with 4 base armor bonus - the highest in the game - (except OL staff which is 5) - to a 700 hp boss that a 13-14 can drop with a corpse that can be recalled is a wise decision

**Comment by Chilly021** [comment]
> I don't think adding a one handed weapon with 4 base armor bonus - the highest in the game - (except OL staff which is 5) - to a 700 hp boss that a 13-14 can drop with a corpse that can be recalled is a wise decision

Can you offer a compromise because we've been batting this around a lot. We said this area due to how difficult the area is on voice comms. The other two PRs did not make sense. There is not another boss other than sword master really or re use another boss to out it on.

**Comment by Wirednuke** [comment]
> I don't think adding a one handed weapon with 4 base armor bonus - the highest in the game - (except OL staff which is 5) - to a 700 hp boss that a 13-14 can drop with a corpse that can be recalled is a wise decision
> 
> EDIT: Add it to swordmaster imo. (and buff black rapier but 🤷 )

We talked about adding it to the swordmaster, but currently I can't kill the swordmaster on my 22/WS thief. I wanted to be able to test it lol. I'm ok if it ends up there eventually or gets its own lair but for now I just wanted to get it in game to see if it's even viable or broken. 

Stat wise it's less powerful than the Fan that can currently be recalled back on Shid's body and looted by a level 3.

**Comment by SewerCzar** [comment]
> thief

I could go on for a while about fan. Is swordmaster killable with two people right now? 

It's a really powerful blocker...

> > I don't think adding a one handed weapon with 4 base armor bonus - the highest in the game - (except OL staff which is 5) - to a 700 hp boss that a 13-14 can drop with a corpse that can be recalled is a wise decision
> 
> Can you offer a compromise? We've been batting this around a lot. We said this area due to how difficult the area is on voice comms. The other two PRs did not make sense. There is not another boss other than sword master really or re use another boss to put it on?

Put it on Carfel as his offhand? I'd be into that. Keep it thief only for now see how it pans out?

**Comment by Wirednuke** [comment]
> 

I'm willing to make that change as a compromise if everyone else is cool with it.

**Comment by SewerCzar** [comment]
> > 
> 
> I'm willing to make that change as a compromise if everyone else is cool with it.

I actually like it. Let's drop Carfel's body by 4 if you do it (or less if he's being hit 99% of the time right now anyway) to compensate for the new blocker

**Comment by Wirednuke** [comment]
- removed from liches, added to carfel
- removed 2 dodge... carfel was a little easy as he was.

**Review by SewerCzar — APPROVED** [review]

**Comment by dedmist** [comment]
> I don't think adding a one handed weapon with 4 base armor bonus - the highest in the game - (except OL staff which is 5) - to a 700 hp boss that a 13-14 can drop with a corpse that can be recalled is a wise decision
> 
> EDIT: Add it to swordmaster imo. (and buff black rapier but 🤷 

I'm agreeing that the entire weapon progression is messed up and needs to be thought out from end to end.  All end-game weapons should be behind one or more bosses and require the kill.

However, I don't think we're yet in the position to make those sweeping changes, which is why I'm OK with this solution... for now.

If I can get enough agreement, we'll rethink the entire amount of game item progression, which should be more rewarding and goal oriented overall.  Twinking will be a little more effective to a point while still giving reward goals with a better progression system.

**Review by dedmist — APPROVED** [review]
Ya, I can be onboard with a Carfel change

**Review by Chilly021 — APPROVED** [review]

**Pull request merged**
