### PR TITLE
BB overgrown temple

### PR DESCRIPTION
**Pull request by Miidgiit**
added an overgrown temple.
fixed bridges not being solid.
slightly added more mobs to Pit
Poison immunity added to Plaguesayer
The Bloodqueen is back
Kesmai -5: portal is solid now

### CODE REVIEW

**Comment by Miidgiit** [comment]
Take your time with this one. i hopefully made all the new mobs correctly.

**Comment by Chilly021** [comment]
Waiting on Lux to get back from trip for approval. Just making sure not to bring down server in his absence.

**Comment by Chilly021** [comment]
@Miidgiit conflicts now.

**Comment by Chilly021** [comment]
Closing. I have advised that this not easily salvaged due to the portion of the region code that is being edited has been stepped all over. I would cut a fresh branch and grab what you can from here, but do not copy anything more than just components. It should track, but otherwise, redo from scratch.

**Pull request closed without merging**
