### PR TITLE
Remade Kes UD

### PR DESCRIPTION
**Pull request by SlysterLOK**

### CODE REVIEW

**Comment by Chilly021** [comment]
Give me till the morning typically when I can do a few of the PRs.

**Comment by SlysterLOK** [comment]
> Give me till the morning typically when I can do a few of the PRs.

No worries. I may not even be around the next few days if many things are wrong. No rush.

**Comment by Chilly021** [comment]
Two minor notes: 

1) You might want to make all outer walls indestructible. 

image
image

2) There is a huge spot where no crits are, just making sure that was intentional. 
image

3) Walls are breakable but component is overlayed with a static. 
image
image

4) Outer walls of boss area (two corners) are breakable
image

5) I like this, but you might need a Lux approval for -3? I see three different entrances. (-4, -3 and Ydnac)
image

**Comment by SlysterLOK** [comment]
Yeah looking at those screenshots this is about 3 or 4 versions behind. Not sure what happened. Tomorrow I'll be able to look

**Comment by sproatba** [comment]
Need to take a closer look at this one, hopefully I can later today.  When this goes we'll need to make sure to fix kes -5 as this pr is deleting it.  Will also need to look at the test region.   In general we need to watch having multiple people in the same map for anything more than quick changes as it's easy to nuke each others work.

**Comment by Chilly021** [comment]
Great job on the clean up!

**Review by Chilly021 — APPROVED** [review]

**Review by Leolus — APPROVED** [review]

**Comment by Chilly021** [comment]
Actually - this might be a good point from @sproatba  
image

**Comment by SlysterLOK** [comment]
> Actually - this might be a good point from @sproatba image

I don't know why dungeon 5 doesn't exist. It is up to date with the master as far as I can tell. Not sure why an empty level was pushed through anyway.

**Comment by Chilly021** [comment]
Let me see if I can figure it out. Might be a quick fix. Midgits map was originally a stand alone. To get visibility and testing the attachment was to add it to under -4. No population. Similar to axe ud and grove originally.

**Comment by Chilly021** [comment]
I have all the changes merged into a local branch off your fork. I do not have access to your fork obviously to commit this branch though. Holler, and we will get this stuff sorted. 

image
image

**Review by sproatba — APPROVED** [review]

**Comment by Chilly021** [comment]
Fixed with this https://github.com/jkachhad/Stormhalter/pull/1676

**Pull request closed without merging**
