### PR TITLE
Add Changes for Staff Revamp

### PR DESCRIPTION
**Pull request by Chilly021**
Add staff revamp:

* All Staffs (not spears) get a +2 to base Armor
* The OL staff gets a bigger upgrade, since it is known to many as the block staff. 
* Tire Iron gets a small buff in attack = bbs due to effort.

### CODE REVIEW

**Review by SewerCzar — COMMENTED** [review]
-1 Skeletons gonna fuck people up dawg.

**Comment by SewerCzar** [comment]
> Do Skeletons have a tire iron? I didn't make any changes to spears though.

image

**Review by SewerCzar — COMMENTED** [review]
As for everything else, I'd make tire iron +3 attack +4 armor and I'd be quite happy with these changes

**Comment by Chilly021** [comment]
> As for everything else, I'd make tire iron +3 attack +4 armor and I'd be quite happy with these changes

Okay, should be fixed on the Spears. My B.

**Review by Leolus — DISMISSED** [review]
Make sure we notify that minotaur's will be meaner

**Comment by Chilly021** [comment]
> Make sure we notify that minotaur's will be meaner

So I believe the Chaotic Staff is separate, at least I'm hoping!

**Review by SewerCzar — DISMISSED** [review]

**Review by Leolus — APPROVED** [review]

**Review by SewerCzar — APPROVED** [review]

**Pull request merged**
