### PR TITLE
Vlad has a ring

### PR DESCRIPTION
**Pull request by SewerCzar**
The autocrat himself found a tool that is very useful and hoards it in his tower. It can transmute minerals into large amounts of gold.

### CODE REVIEW

**Comment by Chilly021** [comment]
@yarrim  - Take a look, we had some discussion today in the channel: https://discord.com/channels/577503035526348810/577503035526348812/965995560718970920

Please let us know if you were working on a quest or are you good with this?

**Comment by sproatba** [comment]
I'm thinking we should make a vlad treasures and put torc and ring in there or something.

**Review by yarrim — APPROVED** [review]
I have not done anything to create a quest, other than suggest that anywhere this ring is placed is fairly accessible to all classes.

My OG memory of Vlad is that he is not a trivial boss, so anyone wanting this ring is probably taking a few companions. I see no reason this ring can't land here.

**Review by yarrim — APPROVED** [review]
See comments in PR thread.
...
I was trying to 'approve' of the 'change requested' from Chilly above. I guess I don't understand that function.

**Review by Chilly021 — APPROVED** [review]

**Pull request merged**
