### PR TITLE
Feature/ud axe enhancements

### PR DESCRIPTION
**Pull request by Chilly021**
* Base Crits had PC immunity. It seems that was a copy and paste issue from Draugr? 
* CGs can hit the Dragon as well. Can't just have one tank.. that is Mama. 
* WW Immunity for Giants since they are flagged as a mini boss.

### CODE REVIEW

**Review by SewerCzar — COMMENTED** [review]
The humanoid undead are poison immune on purpose, which doesn't cover poison cloud, so that's specifically added.

The frost giants are "mini boss stat mobs" but there is No reason for them to be immune to WW.

There's no reason for ice dragon to be weak to CGs but if you want to put that in it's fine.

**Review by dedmist — COMMENTED** [review]
The melee draugr are immune to poison and PC, now just immune to poison.  I think it needs to be all or nothing.  The archer draugr not having immunity seems fine.

If there's an undead dragon that can't be hit by a thaum then I think we probably need to re-evaluate the lair boss.

yup, agreed on miniboss.

I'm not opposed to these changes, but I would prefer some tweaks.

**Comment by SewerCzar** [comment]
> The melee draugr are immune to poison and PC, now just immune to poison. I think it needs to be all or nothing. The archer draugr not having immunity seems fine.
> 
> If there's an undead dragon that can't be hit by a thaum then I think we probably need to re-evaluate the lair boss.
> 
> yup, agreed on miniboss.
> 
> I'm not opposed to these changes, but I would prefer some tweaks.

Undead Dragon is an undead ice dragon thats spawned when certain conditions are met on the Necro - Hard mode essentially. It's meant as a group encounter. Necro himself is hittable by every class.

**Comment by dedmist** [comment]
> > The melee draugr are immune to poison and PC, now just immune to poison. I think it needs to be all or nothing. The archer draugr not having immunity seems fine.
> > If there's an undead dragon that can't be hit by a thaum then I think we probably need to re-evaluate the lair boss.
> > yup, agreed on miniboss.
> > I'm not opposed to these changes, but I would prefer some tweaks.
> 
> Undead Dragon is an undead ice dragon thats spawned when certain conditions are met on the Necro - Hard mode essentially. It's meant as a group encounter. Necro himself is hittable by every class.

I don't believe this addresses my concern, Necro being hit-able by a thaum doesn't seem to help that the Undead Dragon can't be hit by a thaum without a SGA.  And, of course, has thief utility been considered in this encounter?

To be honest, I think anything tailored to be a group hunt needs to have utility or necessity of each class.  Like why should we even have icies for a thief if they can't really participate?  Whereas cloud dragon scales require a thief to get and thus has great utility.  Thieves don't even make good extra hit boxes, they're more of a liability in lairs, I think we'd be better off considering particular tactics and fight mechanics for the hardest bosses.

**Comment by SewerCzar** [comment]
> > > The melee draugr are immune to poison and PC, now just immune to poison. I think it needs to be all or nothing. The archer draugr not having immunity seems fine.
> > > If there's an undead dragon that can't be hit by a thaum then I think we probably need to re-evaluate the lair boss.
> > > yup, agreed on miniboss.
> > > I'm not opposed to these changes, but I would prefer some tweaks.
> > 
> > 
> > Undead Dragon is an undead ice dragon thats spawned when certain conditions are met on the Necro - Hard mode essentially. It's meant as a group encounter. Necro himself is hittable by every class.
> 
> I don't believe this addresses my concern, Necro being hit-able by a thaum doesn't seem to help that the Undead Dragon can't be hit by a thaum without a SGA. And, of course, has thief utility been considered in this encounter?
> 
> To be honest, I think anything tailored to be a group hunt needs to have utility or necessity of each class. Like why should we even have icies for a thief if they can't really participate? Whereas cloud dragon scales require a thief to get and thus has great utility. Thieves don't even make good extra hit boxes, they're more of a liability in lairs, I think we'd be better off considering particular tactics and fight mechanics for the hardest bosses.

I'm entirely unaware of what your concern actually is. Have you done this boss? He's been in the game since August as is.

The boss isn't a "bring every class" boss. But every class can participate in every stage of the encounter? It's just the unnecessary hard mode addition requires SGA or Ice Spear.

If SGA being the only weapon that can hit a boss why aren't you complaining about mama?

Why is this an argument? I was just responding to Chilly.

**Comment by dedmist** [comment]
Mama also isn't a good encounter, especially because it give a critical piece of equipment and 2 classes can't meaningfully participate and one class - that I suppose you could argue doesn't need the equipment generally picks a minor role.

**Comment by Chilly021** [comment]
Just to circle back, all Draugr actually still have PC immunity. I only changed all others. The issue is Draugr base implementation was copy and pasted on quite a few crits down there. I am just correcting it from a "uniqueness" standpoint. Again Draugr are still immune to PC.

**Comment by Chilly021** [comment]
Okay I'll move the PC immunity out.. and add it back to another PR. Skeletons and Spectres are a copy and paste right now with PC immunity.

**Comment by SewerCzar** [comment]
Honestly you can take PC immunity off I just didnt think it made sense for undead to be poisoned. Ideally turn undead would be really effective on them but I hear it's not great

**Pull request closed without merging**
