### PR TITLE
Update Kesmai.mapproj

### PR DESCRIPTION
**Pull request by SlysterLOK**
REMOVAL of -3.5 Prince Godwyn and Bedwyn and reworked their tomb areas. I think I got all of the associated spawns and entity entry out

They really served no purpose and were out of place.

### CODE REVIEW

**Review by Chilly021 — DISMISSED** [review]

**Comment by Tenscore** [comment]
You might need to re-do this one.  Dr. Taylor moseyed in and outdated this Kesmai map.
Sorry.

**Comment by SlysterLOK** [comment]
> You might need to re-do this one. Dr. Taylor moseyed in and outdated this Kesmai map. Sorry.

Well darn. I updated, edited and pushed all in an hour or so at the time. I'll do the same today.

**Comment by SlysterLOK** [comment]
Alright. I pulled and updated and pushed again. Maybe that will help clear up any potential issues.

**Comment by Chilly021** [comment]
Just putting this out there. I'm taking myself off of approver until the Halloween event has either expired or the changes have stopped. This is just to make sure we are not causing any fun weirdness here. 

You may reach out to @jkachhad  otherwise, if you need quicker feedback.

**Review by Chilly021 — APPROVED** [review]

**Review by sproatba — APPROVED** [review]

**Review by zrikzlok — APPROVED** [review]

**Pull request merged**
