### PR TITLE
Added immunity to base vendor model

### PR DESCRIPTION
**Pull request by SewerCzar**
Will go back and clean up NPCs later to remove individual immunities

### CODE REVIEW

**Comment by Chilly021** [comment]
Not sure the purpose around this? We removed some of the immunities originally due to scripting in peaks. Vendors with immunity just sounds like we will have a few people just casting without adventurers bonus. I'd prefer them have like 1 health and die personally.

**Comment by SewerCzar** [comment]
> Not sure the purpose around this? We removed some of the immunities originally due to scripting in peaks. Vendors with immunity just sounds like we will have a few people just casting without adventurers bonus. I'd prefer them have like 1 health and die personally.

Every vendors stock is reset when they die.

 It's just notably that UK ones are being manually restocked right now. And we can't have "rare goods" when players can force reset,

Also peak invulnerabilities were never removed, and I added the invulnerability to axe/kes ones post-peaks

**Comment by Leolus** [comment]
I think vendors should be immune and just not grant skill on attack. Either way most vendors are already immune so this change doesn't really impact the current state of the game, just makes it easier later on so you don't have to remember to do it for each vendor.

**Review by Leolus — APPROVED** [review]

**Comment by Chilly021** [comment]
I think you disabled the Thaums up front in town due to scripters were using them as meat shields.

**Review by yarrim — APPROVED** [review]

**Pull request merged**
