### PR TITLE
Add Max Range to see if this actually is usable to KHally

### PR DESCRIPTION
**Pull request by Chilly021**
Add Max Range to see if this actually is usable to KHally

### CODE REVIEW

**Comment by trlook** [comment]
I suspect there would need to be client tweaks to make this work

**Comment by Chilly021** [comment]
Quite possibly. I did see the property exposed on the props. So it has me wondering.

**Review by dedmist — CHANGES_REQUESTED** [review]
I only see MaxRange being implemented in the Gauntlets base class that doesn't inherit directly from Weapon, so I'm not entirely sure that this is valid.  Also note that Lux is using an annotation on Gauntlets.  I'm not sure what he's using the annotation wrapper for, but I'd check on the validity and function first.

		[WorldForge]
		[CommandProperty(AccessLevel.GameMaster)]
		public int MaxRange => 0;

**Comment by Chilly021** [comment]
> I only see MaxRange being implemented in the Gauntlets base class that doesn't inherit directly from Weapon, so I'm not entirely sure that this is valid. Also note that Lux is using an annotation on Gauntlets. I'm not sure what he's using the annotation wrapper for, but I'd check on the validity and function first.
> 
> ```
> 	[WorldForge]
> 	[CommandProperty(AccessLevel.GameMaster)]
> 	public int MaxRange => 0;
> ```

Good point on the annotation.

**Pull request closed without merging**
