### PR TITLE
Kesmai early progression update

### PR DESCRIPTION
**Pull request by sproatba**
armor progression fix, there is now a clear prgression of armors for the early (pre dragon scale) armors
skulls now only come from lairs in kes.
Trog difficulty reduced to incorporate into armor and skull path.

Implemented some purpose for jackets.  Can be used until robes become better or by ma pre kimono.

Removed some rings from -3 that dropped before element was encountered

### CODE REVIEW

**Comment by sproatba** [comment]
Still fuzzy on when serizlization is needed, if i need to add it for any of this let me know.

**Comment by Chilly021** [comment]
I don't know about the WB from Sharks. Everything else is pretty much in line. I hesitate with the bigger changes that include resistance bonuses as a "on equip".

**Comment by Leolus** [comment]
> 



> I don't know about the WB from Sharks. Everything else is pretty much in line. I hesitate with the bigger changes that include resistance bonuses as a "on equip".

I don't have an issue with the early game items here. Realistically these things get blown through in a few hours of gameplay.

**Comment by Chilly021** [comment]
> > 
> 
> > I don't know about the WB from Sharks. Everything else is pretty much in line. I hesitate with the bigger changes that include resistance bonuses as a "on equip".
> 
> I don't have an issue with the early game items here. Realistically these things get blown through in a few hours of gameplay.

I mean this is basically a MA item again, just like the Grizzly Jacket.

**Comment by sproatba** [comment]
> What's the reasoning behind Trogg having a 40% damage reduction and -100 AR?
> 
> If that's considered reasonable his other rewards have to go down by a significant amount.

trog was out of line with the progression, there was no reason to go to him aside from his armor, and his armor wasn't even really in a good spot due to the need for fire protection.  he's now meant to  be hit up earlier, and you don't have a tiger skull to go after him with.  He also now has a +2 mace to offset him a bit.  now you get armor and a skull, and can do him as a stepping stone into -3 which is a large difficulty jump.

**Comment by sproatba** [comment]
> > > 
> > 
> > 
> > > I don't know about the WB from Sharks. Everything else is pretty much in line. I hesitate with the bigger changes that include resistance bonuses as a "on equip".
> > 
> > 
> > I don't have an issue with the early game items here. Realistically these things get blown through in a few hours of gameplay.
> 
> I mean this is basically a MA item again, just like the Grizzly Jacket.

all classes can use this before getting a robe, and big bear is killable before -4 is huntable.  It will get outclassed by robes for magic users, but you may want to swap to it for kosh for the fire boost over a robe giving itemization choices and early game fire protection which is needed.

**Comment by sproatba** [comment]
> Is there a plan for blind and ice prot? I don't see them appearing in an accessible place in leng or axe.

ice ring drops on -4 where ice is first encountered in kes, it also drops in axe pretty regularly.  Blind drops in -4 as well.  If needed, it can be added to early levels of one of the other lands as well.   From a progression standpoint, the other lands are reachable starting with access to -3 or the deep forest which should be similar to -3 difficulty (it's not currently unless you hit big.bear)  early levels of other lands can be hit between -3 and -4 to encounter the -4 effects one at a time instead of all at once.

**Review by Leolus — APPROVED** [review]

**Review by SewerCzar — COMMENTED** [review]
Trogg does not need changes. You can make a character, get a sack of balms, walk to him killing only the monsters on the way and kill him.

Things shouldn't be nerfed for no reason.

[TroggTest 2022-03-08 12-08-35.zip](https://github.com/jkachhad/Stormhalter/files/8208247/TroggTest.2022-03-08.12-08-35.zip)

**Comment by sproatba** [comment]
> Trogg does not need changes. You can make a character, get a sack of balms, walk to him killing only the monsters on the way and kill him.
> 
> Things shouldn't be nerfed for no reason.
> 
> [TroggTest 2022-03-08 12-08-35.zip](https://github.com/jkachhad/Stormhalter/files/8208247/TroggTest.2022-03-08.12-08-35.zip)
 very classy.  I'll be sure to look to you for feedback in the future.

**Comment by trlook** [comment]
Just because an MA can do somethings doesn't mean it's balanced.

Lux mentioned having Blind rings Trog and then also making blind reduce DR so getting blind before venturing to -4 would be nice (not everything needs to be catch 22)

**Comment by dedmist** [comment]
In OG, you usually could find a resistance on the level that you needed it, so each new zone had to be played cautiously before you found the item that helped you, but even then it's a 50%ish help.  This mechanic is pretty awesome for the risk-reward scenario and would really go great in Jade.  The exception was for fire in -2 kes and a few prep items here and there.

On the reverse side, twinked characters roll through the area pretty easily and don't feel the progression all that much, not necessarily a bad thing, just they don't have as many progression goals until end game.

**Review by Chilly021 — APPROVED** [review]

**Comment by Chilly021** [comment]
YOU HAVE LIFT OFF @sproatba

**Comment by Leolus** [comment]
image

Such valuable feedback from someone who bases a test off a class that doesn't need to kill trogg.

@jkachhad I think you should consider if Sewer is warranted as a contributor going forward if this is how he wants to communication. Passive aggressive comments in a lor.

**Comment by SewerCzar** [comment]
> Just because an MA can do somethings doesn't mean it's balanced.
> 
> Lux mentioned having Blind rings Trog and then also making blind reduce DR so getting blind before venturing to -4 would be nice (not everything needs to be catch 22)

[TroggTest 2022-03-08 15-11-19.zip](https://github.com/jkachhad/Stormhalter/files/8209374/TroggTest.2022-03-08.15-11-19.zip)

Thaum died once, he got there before 8 by running straight through stuff. Once he was 8 was np.

**Pull request merged**
