### PR TITLE
Make the traps move after they cast

### PR DESCRIPTION
**Pull request by Wirednuke**
Just experimenting with making the wizard lair traps move after they cast. 

Using OnSpellTarget to start a kill timer for 1 minute. Then the location spawner should take care of the rest. 

Only question: Can invulnerable traps be killed by the Kill command?

### CODE REVIEW

**Comment by Wirednuke** [comment]
Hold off on reviewing, more changes coming and I can't mark as draft on the app

**Comment by Wirednuke** [comment]
Ok we are good now... ready for review:

- Added code to make traps check their location when they spawn for another trap and respawn if they do. 
- After traps cast they will kill themselves and respawn at a different location
- Changed traps from IsInvisible to IsHiding and added Level's hoping that they are hidden but able to detect each other. 
- Added a mechanism in OnIncomingPlayer method that unhides the trap when a sufficiently leveled thief is in proximity.

**Review by Chilly021 — APPROVED** [review]

**Review by zrikzlok — DISMISSED** [review]

**Comment by sproatba** [comment]
Seems to me just having the trap kill itself and giving it a region to spawn in would make it move,  making it teleport around and whatnot seems overly complicated to me.

**Review by sproatba — APPROVED** [review]

**Comment by Wirednuke** [comment]
Hold on... don't merge.. conflicts now for some reason

**Review by Chilly021 — APPROVED** [review]

**Review by zrikzlok — APPROVED** [review]

**Review by sproatba — APPROVED** [review]

**Pull request merged**
